### ISSUE TITLE
yargs-parser crashes when passed a `--toString` option

### ISSUE THREAD

**Issue by mleguen** [yargs/yargs-parser#228]
Follow-up of the bugs fixed by #227.

With a code as simple as:
```jsconst Parser = require('yargs-parser')
Parser(process.argv.slice(2))
```

yargs-parser crashes on a `--toString` option:
```bash
$ node index.js --toString
...\yargs\yargs-parser\index.js:426
      flags.aliases[key].forEach(function (x) {
                         ^

TypeError: flags.aliases[key].forEach is not a function
    at setArg (C:\Users\pwhl824\Dev\yargs\yargs-parser\index.js:426:26)
    at parse (C:\Users\pwhl824\Dev\yargs\yargs-parser\index.js:202:11)
    at Parser (C:\Users\pwhl824\Dev\yargs\yargs-parser\index.js:960:16)
    at Object.<anonymous> (C:\Users\pwhl824\Dev\yargs\yargs-parser-tests\index.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
```

**Comment by mleguen** [comment]
Basically, what needs to be done is to ban the use of `xxx[key]` when `key` is a parsed key, as it could be the name of a method from Object.prototype (or Array.prototype if `xxx` is an array), and use instead `xxx.hasOwnProperty(key) ? xxx[key] : undefined` (`xxx.includes[key] ? xxx[key] : undefined` for an array).

**Comment by mleguen** [comment]
And stop using on these objects (or arrays) the methods from Object.prototype (or Array.prototype), as they could already have been replaced.

**Comment by bcoe** [comment]
@mleguen great catch 👌 it was actually a pretty big hassle to fix this 😄 

I went ahead and landed the update, with tons of tests (since there were a couple other bugs I wanted to address this weekend, and fixing prototypes touched a ton of the codebase).

**Comment by mleguen** [comment]
@bcoe Great job, thank you! Using `Object.create(null)` as you did is far more interesting that what I suggested here.
