### ISSUE TITLE
Can't build locally

### ISSUE THREAD

**Issue by tommy-mitchell** [yargs/yargs-parser#475]
On a fresh copy of the repo, running the `build:cjs` script fails with an error from `rollup-plugin-ts`:

```
[!] (plugin Typescript) Error: Debug Failure. Unhandled SyntaxKind: Unknown.
```

<details>
<summary>Error Log</summary>

```sh
./lib/index.ts → ./build/index.cjs...
DeprecationWarning: 'createExportAssignment' has been deprecated since v4.0.0. Use the appropriate method on 'ts.factory' or the 'factory' supplied by your transformation context instead.
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
util (imported by lib/index.ts)
path (imported by lib/index.ts)
fs (imported by lib/index.ts)
[!] (plugin Typescript) Error: Debug Failure. Unhandled SyntaxKind: Unknown.
Error: Debug Failure. Unhandled SyntaxKind: Unknown.
    at pipelineEmitWithHintWorker (.../yargs-parser/node_modules/typescript/lib/typescript.js:113127:22)
    at pipelineEmitWithHint (.../yargs-parser/node_modules/typescript/lib/typescript.js:112660:17)
    at pipelineEmitWithComments (.../yargs-parser/node_modules/typescript/lib/typescript.js:116301:13)
    at pipelineEmit (.../yargs-parser/node_modules/typescript/lib/typescript.js:112600:13)
    at emitExpression (.../yargs-parser/node_modules/typescript/lib/typescript.js:112584:13)
    at emitExportAssignment (.../yargs-parser/node_modules/typescript/lib/typescript.js:114585:13)
    at pipelineEmitWithHintWorker (.../yargs-parser/node_modules/typescript/lib/typescript.js:112873:32)
    at pipelineEmitWithHint (.../yargs-parser/node_modules/typescript/lib/typescript.js:112660:17)
    at pipelineEmitWithComments (.../yargs-parser/node_modules/typescript/lib/typescript.js:116301:13)
    at pipelineEmit (.../yargs-parser/node_modules/typescript/lib/typescript.js:112600:13)
```

</details>

**Comment by tommy-mitchell** [comment]
Slightly related, `rollup-plugin-ts` v3.2.0 includes breaking changes (drops support for Node 14, see https://github.com/wessberg/rollup-plugin-ts/issues/202), but rolling back to v3.1.1 doesn't fix this build issue.

**Comment by tommy-mitchell** [comment]
Just saw #470 and #471, whoops, guess I didn't look hard enough. Closing as duplicate.
